# Generated by Django 5.0.1 on 2024-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='github_repo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='zipfile',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
